services:
  eddi:
    image: labsai/eddi:latest
    environment:
      - "EDDI_VAULT_MASTER_KEY=${EDDI_VAULT_MASTER_KEY:-}"
      - "EDDI_DATASTORE_TYPE=${EDDI_DATASTORE_TYPE:-mongodb}"
#      - "JAVA_OPTS_APPEND=-Dquarkus.http.cors.origins=http://localhost:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${EDDI_PORT:-7070}:7070"
      - "${EDDI_HTTPS_PORT:-7443}:7443"
#      - "5005:5005"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongodb-db:/data/db

volumes:
  mongodb-db:
