services:
  eddi:
    image: labsai/eddi:6
    environment:
      - "EDDI_VAULT_MASTER_KEY=local-dev-key-change-in-production"
#      - "JAVA_OPTS_APPEND=-Dquarkus.http.cors.origins=http://localhost:3000"
    ports:
      - "7070:7070"
      - "7443:7443"
#      - "5005:5005"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongodb-db:/data/db

volumes:
  mongodb-db:
