export const CONVERSATION_READY = 'READY';
export const CONVERSATION_ENDED = 'ENDED';
export const CONVERSATION_IN_PROGRESS = 'IN_PROGRESS';
export const CONVERSATION_ERROR = 'ERROR';
export const CONVERSATION_EXECUTION_INTERRUPTED = 'EXECUTION_INTERRUPTED';
