version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - "7070:7070"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.4
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 128m
      EDDI_MEMORY_MAX: 128m
      #EDDI_JAVA_ENV_MONGODB_HOST: mongodb.hosts=mongodb
  eddi-config-ui:
    image: labsai/eddi-config-ui:latest
    ports:
    - "3000:3000"
    links:
    - eddi
    depends_on:
    - eddi
    environment:
      EDDI_API_URL: "http://eddi:7070"
      PORT: 3000
  mongodb:
    image: mongo:3.6
    restart: always
