version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - '7070:7070'
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.4
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 128m
      EDDI_MEMORY_MAX: 128m
  eddi-config-ui:
    image: labsai/eddi-config-ui:latest
    ports:
      - '7071:7071'
    links:
      - eddi
    depends_on:
      - eddi
    environment:
      EDDI_API_URL: 'http://localhost:7070'
      READ_ONLY_DOMAIN: 'https://app.labs.ai'
      PORT: 7071
  mongodb:
    image: mongo:3.6
    restart: always
