export enum ModalEnum {
  'createBot',
  'editBot',
  'createPackage',
  'editPackage',
  'updatePackage',
  'addPackages',
  'editJson',
  'addPlugins',
  'viewJson',
  'createNewConfig',
  'createNewConfig2',
  'updatePackages',
  'updateBots',
  'confirmation',
  'error',
  'addNewPackageToBot',
}
