/*
 * Copyright EDDI contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package ai.labs.eddi.engine.internal;

import ai.labs.eddi.engine.runtime.BoundedLogStore;
import ai.labs.eddi.engine.runtime.IDatabaseLogs;
import ai.labs.eddi.engine.runtime.InstanceIdProducer;
import ai.labs.eddi.utils.LogCaptureSupport;
import jakarta.ws.rs.sse.Sse;
import jakarta.ws.rs.sse.SseEventSink;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import static ai.labs.eddi.utils.LogCaptureSupport.assertNoForgedRecordBoundary;
import static ai.labs.eddi.utils.LogCaptureSupport.captureLogsOf;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * CWE-117 regression tests for {@link RestLogAdmin}'s SSE stream-started line
 * (code scanning alerts #105 and #106).
 *
 * <p>
 * {@code agentId} and {@code level} are {@code @QueryParam}s on
 * {@code GET /logs/stream} and reach the line verbatim, so a caller that puts a
 * CRLF in either closes the real record and has the remainder read as a second,
 * server-authored entry. The irony is specific to this endpoint: it is the log
 * <em>viewer</em>, so the forged line is served straight back to whoever is
 * tailing the stream.
 * </p>
 *
 * <p>
 * {@code listenerId} on the same line is deliberately left unsanitized and is
 * not asserted on — it is generated by {@link BoundedLogStore}, never supplied
 * by the caller, and CodeQL did not flag it.
 * </p>
 */
@DisplayName("RestLogAdmin log injection (CWE-117)")
class RestLogAdminLogInjectionTest {

    /**
     * A frozen clock keeps the cleanup thread parked in its 2-second sleep for the
     * whole capture window: it can neither reach the heartbeat branch nor fall out
     * of the max-lifetime loop, so the only line inside the window is the one under
     * test. Without that, the thread's own "listener removed" line could race into
     * the capture and satisfy the assertion in place of the real subject.
     */
    private static final long FROZEN_CLOCK = 1_000_000L;

    private final AtomicBoolean sinkClosed = new AtomicBoolean(false);

    private SseEventSink eventSink;
    private Sse sse;
    private RestLogAdmin restLogAdmin;

    @BeforeEach
    void setUp() {
        BoundedLogStore boundedLogStore = mock(BoundedLogStore.class);
        eventSink = mock(SseEventSink.class);
        sse = mock(Sse.class);

        // No backlog, so no sendEvent call can log inside the window either.
        when(boundedLogStore.getEntries(any(), any(), any(), anyInt())).thenReturn(List.of());
        when(boundedLogStore.addListener(any())).thenReturn("listener-1");
        when(eventSink.isClosed()).thenAnswer(invocation -> sinkClosed.get());

        restLogAdmin = new RestLogAdmin(boundedLogStore, mock(IDatabaseLogs.class), mock(InstanceIdProducer.class),
                () -> FROZEN_CLOCK);
    }

    @AfterEach
    void releaseTheCleanupThread() {
        // The virtual thread loops for as long as the sink is open; closing it lets
        // the thread finish rather than outlive the test.
        sinkClosed.set(true);
    }

    @Test
    @DisplayName("a forged agentId cannot forge a record on the stream-started line")
    void sanitizesTheAgentIdOnTheStreamStartedLine() {
        String forgedAgentId = "agent-1" + LogCaptureSupport.FORGED_RECORD;

        List<String> logged = captureLogsOf(RestLogAdmin.class,
                () -> restLogAdmin.streamLogs(forgedAgentId, null, "INFO", eventSink, sse));

        assertNoForgedRecordBoundary(logged, "RestLogAdmin's SSE stream-started line (agentId)");
        assertTrue(logged.stream().anyMatch(value -> value.contains("agent-1")),
                "the agentId is sanitized, not dropped — an operator still needs to know which agent: " + logged);
    }

    @Test
    @DisplayName("a forged level cannot forge a record on the stream-started line")
    void sanitizesTheLevelOnTheStreamStartedLine() {
        String forgedLevel = "INFO" + LogCaptureSupport.FORGED_RECORD;

        List<String> logged = captureLogsOf(RestLogAdmin.class,
                () -> restLogAdmin.streamLogs("agent-1", null, forgedLevel, eventSink, sse));

        assertNoForgedRecordBoundary(logged, "RestLogAdmin's SSE stream-started line (level)");
        assertTrue(logged.stream().anyMatch(value -> value.contains("INFO")),
                "the level is sanitized, not dropped: " + logged);
    }
}
