import { CSSProperties } from 'react';
import {
  DARK_BLUE_BORDER,
  DARK_BLUE_COLOR,
  DARK_GREY_COLOR,
  GREY_BORDER,
  LIGHT_GREY_COLOR,
  LIGHT_GREY_COLOR2,
  LIGHT_GREY_COLOR3,
  MEDIUM_FONT,
  MEDIUM_FONT3,
  SMALL_FONT,
} from '../../../styles/DefaultStylingProperties';

const styles: CSSProperties = {
  conversation: {
    ':hover': {
      backgroundColor: LIGHT_GREY_COLOR3,
    },
    display: 'flex',
    borderBottom: GREY_BORDER,
    paddingBottom: '2px',
    marginTop: '8px',
    cursor: 'pointer',
    width: '100%',
  },
  conversationName: {
    color: DARK_GREY_COLOR,
    fontSize: MEDIUM_FONT3,
    display: 'block',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
  },
  conversationVersion: {
    backgroundColor: LIGHT_GREY_COLOR2,
    borderRadius: '100px',
    color: DARK_BLUE_COLOR,
    fontSize: MEDIUM_FONT,
    height: '21px',
    marginLeft: '15px',
    padding: '2px 10px',
    textAlign: 'center',
    width: 'fit-content',
    lineHeight: '17px',
  },
  nameAndVersion: {
    display: 'flex',
    maxWidth: '300px',
  },
  environment: {
    color: DARK_GREY_COLOR,
    fontSize: SMALL_FONT,
    height: '20px',
    marginTop: '2px',
    whiteSpace: 'nowrap',
    textAlign: 'left',
    minWidth: '80px',
    marginRight: '15px',
  },
  conversationState: {
    color: DARK_GREY_COLOR,
    fontSize: SMALL_FONT,
    height: '20px',
    marginTop: '2px',
    whiteSpace: 'nowrap',
    textAlign: 'left',
    minWidth: '110px',
    marginRight: '20px',
  },
  conversationStepSizeContainer: {
    minWidth: '80px',
    marginLeft: 'auto',
  },
  conversationStepSize: {
    color: DARK_BLUE_COLOR,
    fontSize: MEDIUM_FONT,
    borderRadius: '100px',
    height: '21px',
    padding: '2px 5px',
    border: DARK_BLUE_BORDER,
    lineHeight: '16px',
    display: 'table',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  createdOn: {
    color: DARK_GREY_COLOR,
    textAlign: 'right',
    fontSize: SMALL_FONT,
    height: '20px',
    marginTop: '2px',
    whiteSpace: 'nowrap',
  },
  lastModifiedOn: {
    color: DARK_GREY_COLOR,
    textAlign: 'left',
    fontSize: SMALL_FONT,
    height: '20px',
    marginTop: '2px',
    whiteSpace: 'nowrap',
    minWidth: '120px',
  },
};
export default styles;
