apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eddi.fullname" . }}-secrets
  labels:
    {{- include "eddi.labels" . | nindent 4 }}
type: Opaque
stringData:
  EDDI_VAULT_MASTER_KEY: {{ .Values.eddi.vaultMasterKey | quote }}
